doc/queries/doc-topologicalSort.queries, doc/topologicalSort/doc-pgr_toplogicalSort.queries, doc/topologicalSort/pgr_topologicalSort.rst, include/topologicalSort/pgr_topologicalSort.hpp, sql/transitiveClosure/CMakeLists.txt, sql/transitiveClosure/_transitiveClosure.sql, sql/transitiveClosure/transitiveClosure.sql, test/topologicalSort/doc-topologicalSort.result, test/topologicalSort/doc-topologicalSort.test.sql
[WIP]
This PR is to track all the modifications done in Week 7.
=> pgr_topologicalSort GSOC-2019 week 7

sql/transitiveClosure/_transitiveClosure.sql
[WIP]
This PR is to track all the modifications done in Week 8.
=> pgr_topologicalSort GSOC-2019 week 8

include/c_types/pgr_topologicalSort_t.h, include/c_types/transitiveClosure_rt.h, include/drivers/transitiveClosure/transitiveClosure_driver.h, include/transitiveClosure/pgr_transitiveClosure.hpp, pgtap/topologicalSort/no_crash_test-topologicalSort.sql, sql/topologicalSort/_topologicalSort.sql, sql/topologicalSort/topologicalSort.sql, sql/transitiveClosure/transitiveClosure.sql, src/topologicalSort/topologicalSort.c, src/transitiveClosure/CMakeLists.txt, src/transitiveClosure/transitiveClosure.c, src/transitiveClosure/transitiveClosure_driver.cpp
[WIP]
This PR is to track all the modifications done in Week 9.
=> pgr_transitiveClosure GSOC-2019 week 9

sql/transitiveClosure/_transitiveClosure.sql, sql/transitiveClosure/transitiveClosure.sql, src/transitiveClosure/transitiveClosure.c
[WIP]
This PR is to track all the modifications done in Week 11.
=> pgr_transitiveClosure GSOC-2019 week 11-PR2

doc/bellman_ford/CMakeLists.txt, doc/bellman_ford/pgr_edwardMoore.rst, docqueries/bellman_ford/doc-pgr_edwardMoore.result, docqueries/bellman_ford/doc-pgr_edwardMoore.test.sql, pgtap/bellman_ford/edwardMoore/edwardMoore-types-check.sql, pgtap/bellman_ford/edwardMoore/no_crash_test-edwardMoore.sql
PR for documentation and test-related commits for pgr_edwardMoore
=> pgr_edwardMoore GSOC-2019 week 11 - Doc/Tests

doc/bellman_ford/pgr_edwardMoore.rst, docqueries/bellman_ford/doc-pgr_edwardMoore.result, docqueries/bellman_ford/doc-pgr_edwardMoore.test.sql, pgtap/bellman_ford/edwardMoore/edwardMoore-compare-dijkstra.sql
[WIP]
This PR is to track any modifications done in Week 12.
=> pgr_edwardMoore GSOC-2019 week 12 

NEWS, configuration.conf, doc/bellman_ford/pgr_edwardMoore.rst, doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst, doc/breadthFirstSearch/pgr_breadthFirstSearch.rst, doc/src/pgRouting-introduction.rst, doc/src/proposed.rst, doc/src/release_notes.rst, docqueries/bellman_ford/doc-pgr_edwardMoore.result, docqueries/breadthFirstSearch/doc-pgr_binaryBreadthFirstSearch.result, docqueries/breadthFirstSearch/doc-pgr_binaryBreadthFirstSearch.test.sql, docqueries/breadthFirstSearch/doc-pgr_breadthFirstSearch.result
[WIP]
This PR is to track any modifications done in Week 12 for pre-deployment.
=> pgr_edwardMoore GSOC-2019 week 12 - Doc

doc/LTDTree/pgr_LTDTree.rst, docqueries/LTDTree/doc-LTDTree.result, docqueries/LTDTree/doc-LTDTree.test.sql, include/LTDTree/pgr_LTDTree_driver.hpp, pgtap/LTDTree/pgr_LTDTree_types_check.sql
=> GSoC-2020- LTDTree() [Week 3] 

include/drivers/spanningTree/mrt_driver.h, include/spanningTree/pgr_mrt_driver.hpp, pgtap/LTDTree/LTDTree-innerQuery.sql, pgtap/LTDTree/ltdtree-edge-cases.sql, pgtap/LTDTree/no_crash_test-LTDTree.sql, pgtap/spanningTree/mrt/mrt-edge-cases.sql, pgtap/spanningTree/mrt/mrt-innerQuery.sql, pgtap/spanningTree/mrt/no_crash_test-mrt.sql, pgtap/spanningTree/mrt/pgr_mrt_types_check.sql, sql/LTDTree/LTDTree.sql, sql/LTDTree/_LTDTree.sql, sql/spanningTree/_mrt.sql, sql/spanningTree/mrt.sql, src/LTDTree/LTDTree.c, src/spanningTree/mrt.c, src/spanningTree/mrt_driver.cpp
=> GSoC-2020- pgr_mrt() [Week 6]

pgtap/bdAstar/bdAstar-rows-check.sql, pgtap/bdAstar/bdAstarCost-rows-check.sql
bdAstar on #68.
- Adds pgTAP tests for bdAstar directory that check the output after rows ordering.
=> Fixing bdAstar ordering issue

pgtap/withPoints/withPoints-rows-check.sql, pgtap/withPoints/withPointsCost-rows-check.sql
withPoints on #68.
- Adds pgTAP tests for withPoints directory that check the output after rows ordering.
=> Fixing withPoints ordering issue

doc/coloring/coloring-family.rst, doc/coloring/pgr_edgeColoring.rst, docqueries/coloring/doc-edgeColoring.result, docqueries/coloring/doc-edgeColoring.test.sql, include/coloring/pgr_edgeColoring.hpp, src/coloring/edgeColoring_driver.cpp
- include/coloring/
- Modified `pgr_edgeColoring.hpp` to connect boost library.
- docqueries/coloring/
- Modified `doc-edgeColoring.result`
- Modified `doc-edgeColoring.test.sql`
- doc/coloring/
- Modified `pgr_edgeColoring.rst`
- Modified `coloring-family.rst`
=> GSoC-2021 Week2: pgr_edgeColoring

doc/coloring/coloring-family.rst, doc/coloring/pgr_edgeColoring.rst, docqueries/coloring/doc-edgeColoring.result, docqueries/coloring/doc-edgeColoring.test.sql, include/coloring/pgr_edgeColoring.hpp, src/coloring/edgeColoring_driver.cpp
=> GSoC-2021 Week3: pgr_edgeColoring

.github/workflows/boost_version.yml, .github/workflows/check-queries.yml, .github/workflows/clang.yml, .github/workflows/doc-check.yml, .github/workflows/documentation.yml, .github/workflows/macos.yml, .github/workflows/publish-doc.yml, .github/workflows/release.yml, include/c_common/arrays_input.h, include/c_common/get_check_data.h, include/c_common/vroom/matrix_input.h, include/c_types/vroom/vroom_matrix_cell_t.h, src/common/arrays_input.c, src/common/get_check_data.c, src/common/vroom/matrix_input.c
- Added function to get positive int array input
- Updated all the GitHub actions build for building VROOM with vrprouting.
- TODO: macOS Build.
- Added functions to get columns data input - Index, MatrixIndex, Duration, Priority, Distance.
=> GSoC-2021 Week 3: vrp_vroom

pgtap/coloring/edgeColoring/edge-cases.sql, pgtap/coloring/edgeColoring/innerQuery.sql, pgtap/coloring/edgeColoring/no_crash_test.sql, pgtap/coloring/edgeColoring/types_check.sql
- **pgtap/coloring/edgeColoring/**
- Modified `innerQuery.sql`
- Modified `types_check.sql`
- Modified `no_crash_test.sql`
- Modified `edge-cases.sql`
=> GSoC-2021 Week4: pgr_edgeColoring

include/coloring/pgr_edgeColoring.hpp, include/drivers/coloring/edgeColoring_driver.h, sql/coloring/_edgeColoring.sql, sql/coloring/edgeColoring.sql, src/coloring/edgeColoring.c, src/coloring/edgeColoring_driver.cpp, src/coloring/pgr_edgeColoring.cpp
- **sql/coloring/**
- Refined `_edgeColoring.sql`
- Refined `edgeColoring.sql`
- **src/coloring/**
- Refined `pgr_edgeColoring.cpp`
- Refined `edgeColoring_driver.cpp`
- Refined `edgeColoring.c`
- **include/coloring/**
- Refined `pgr_edgeColoring.hpp`
- **include/drivers/coloring/**
- Refined `edgeColoring_driver.h`
=> GSoC-2021 Week 7: pgr_edgeColoring

include/drivers/coloring/edgeColoring_driver.h, pgtap/coloring/edgeColoring/edge-cases.sql
- Refined `edge-cases.sql`
-
-
=> GSoC-2021 Week 8: pgr_edgeColoring

doc/general/introduction.rst
[doc/general/introduction.rst] Added my name and email to list of individuals
=> GSoC 2022: Manas Sivakumar Week 1

doc/circuits/CMakeLists.txt, include/c_types/circuits_rt.h, include/drivers/circuits/hawickcircuits_driver.h, sql/circuits/_hawickCircuits.sql, sql/circuits/hawickCircuits.sql, src/circuits/hawickCircuits.c, src/circuits/hawickCircuits_driver.cpp
- [pgr_hawickCircuits] [doc] adding CMakeLists.txt
- [pgr_hawickCircuits] [include] adding c_type circuits_rt.h
- [pgr_hawickCircuits] [src] modifying hawickCircuits.c for arrays
- [pgr_hawickCircuits] Doing some requested changes
=> GSoC 2022: Nitish Chauhan Week 2

sql/metrics/CMakeLists.txt, sql/metrics/_edgeBetweennessCentrality.sql, sql/metrics/_ithBandwidth.sql, sql/metrics/_vertexBetweennessCentrality.sql, sql/metrics/edgeBetweennessCentrality.sql, sql/metrics/ithBandwidth.sql, sql/metrics/vertexBetweennessCentrality.sql
- added CMakeList.txt for the metrics directory in the SQL folder.
- added _edgeBetweennessCentrality.sql
- added edgeBetweennessCentrality.sql
- added _ithBandwidth.sql
- added ithBandwidth.sql
- added _vertexBetweennessCentrality.sql
- added vertexBetweennessCentrality.sql
=> GSoC 2022: Sanskar Bhushan Week 2

include/metrics/pgr_ithBandwidth.hpp
=> GSoC 2022: Sanskar Bhushan Week 3

configuration.conf, doc/ordering/CMakeLists.txt, docqueries/ordering/CMakeLists.txt, docqueries/ordering/cuthillMckeeOrdering.test.sql, docqueries/ordering/test.conf, include/c_types/ordering_rt.h, include/drivers/ordering/cuthillMckeeOrdering_driver.h, include/ordering/cuthillMckeeOrdering.hpp, sql/ordering/CMakeLists.txt, sql/ordering/_cuthillMckeeOrdering.sql, sql/ordering/cuthillMckeeOrdering.sql, src/ordering/CMakeLists.txt, src/ordering/cuthillMckeeOrdering.c, src/ordering/cuthillMckeeOrdering_driver.cpp
- adding c_type for ordering arrays
- adding cuthillMckeeOrdering.hpp in include
- Fixing compilation errors
- adding basic structuring of docqueries files
=> GSoC 2022 : Shobhit Chaurasia Week 3

configuration.conf, include/circuits/hawickcircuits.hpp, src/circuits/CMakeLists.txt, src/circuits/hawickCircuits.c, src/circuits/hawickCircuits_driver.cpp
- Fixing errors in the pipeline
=> GSoC 2022: Nitish Chauhan Week 4

docqueries/ordering/cuthillMckeeOrdering.test.sql, include/drivers/ordering/cuthillMckeeOrdering_driver.h, include/ordering/cuthillMckeeOrdering.hpp, src/ordering/cuthillMckeeOrdering.c, src/ordering/cuthillMckeeOrdering_driver.cpp
- changing cuthillMckeeOrdering.hpp
Still, this file needs to change a lot yet
=> GSoC 2022 : Shobhit Chaurasia Week 4

include/c_types/bc_rt.h
=> GSoC 2022: Sanskar Bhushan Week 4

include/drivers/metrics/edgeBetweennessCentrality_driver.h, include/drivers/metrics/ithBandwidth_driver.h, include/drivers/metrics/vertexBetweennessCentrality_driver.h
- added edgeBetweennessCentrality_driver.h
- added vertexBetweennessCentrality_driver.h
- added ithBandwidth_driver.h
=> GSoC 2022: Sanskar Bhushan Week 5

doc/conf.py.in, doc/ordering/CMakeLists.txt, doc/ordering/cuthillMckeeOrdering.rst, doc/ordering/ordering-family.rst, doc/src/experimental.rst, docqueries/ordering/cuthillMckeeOrdering.result, docqueries/ordering/cuthillMckeeOrdering.test.sql, include/drivers/ordering/cuthillMckeeOrdering_driver.h, include/ordering/cuthillMckeeOrdering.hpp, pgtap/ordering/cuthillMckeeOrdering/edge_cases.pg, pgtap/ordering/cuthillMckeeOrdering/inner_query.pg, pgtap/ordering/cuthillMckeeOrdering/types_check.pg, sql/ordering/_cuthillMckeeOrdering.sql, sql/ordering/cuthillMckeeOrdering.sql, src/ordering/cuthillMckeeOrdering.c
- adding ordering-family.rst
- improved documentation and solved link error
- added basic pgtap files structures
- started working on calling the function without boost example
=> GSoC 2022 : Shobhit Chaurasia Week 6

doc/circuits/hawickCircuits.rst, docqueries/circuits/hawickCircuits.result, include/c_types/circuits_rt.h, include/circuits/hawickcircuits.hpp, pgtap/circuits/hawickCircuits/types_check.pg, sql/circuits/_hawickCircuits.sql, sql/circuits/hawickCircuits.sql, src/circuits/hawickCircuits.c
- work on hawickCircuit.hpp
- modifying documentation to pgRouitng standard
- types_check pgtap test
- change output design to include end_vid
=> GSoC 2022: Nitish Chauhan Week 6

doc/metrics/CMakeLists.txt, doc/metrics/bandwidth-family.rst, doc/metrics/pgr_ithBandwidth.rst
- added CMakeLists.txt for metrics docs.
- added pgr_ithBandwidth.rst.
- added bandwidth-family.rst.
=> GSoC 2022: Sanskar Bhushan Week 6

include/c_types/bc_rt.h, include/drivers/metrics/edgeBetweennessCentrality_driver.h, include/drivers/metrics/ithBandwidth_driver.h, include/drivers/metrics/vertexBetweennessCentrality_driver.h, include/metrics/pgr_edgeBetweennessCentrality.hpp, include/metrics/pgr_ithBandwidth.hpp, include/metrics/pgr_vertexBetweennessCentrality.hpp, sql/metrics/_ithBandwidth.sql, sql/metrics/ithBandwidth.sql, src/metrics/CMakeLists.txt, src/metrics/edgeBetweennessCentrality.c, src/metrics/edgeBetweennessCentrality_driver.cpp, src/metrics/ithBandwidth.c, src/metrics/ithBandwidth_driver.cpp, src/metrics/vertexBetweennessCentrality.c, src/metrics/vertexBetweennessCentrality_driver.cpp
- Complete logical implementation of all the desired GSoC functions.
=> Sanskar week 8

include/drivers/metrics/ithBandwidth_driver.h, include/metrics/pgr_ithBandwidth.hpp, sql/metrics/_ithBandwidth.sql, sql/metrics/ithBandwidth.sql, src/metrics/ithBandwidth.c, src/metrics/ithBandwidth_driver.cpp
- [include][drivers][metrics] modified ithBandwidth_driver.h
- [include][metrics] modified pgr_ithBandwidth.hpp
- [sql][metrics] modified _ithBandwidth.sql
- [sql][metrics] modified ithBandwidth.sql
- [src][metrics] modified ithBandwidth.c
- [src][metrics] modified ithBandwidth_driver.cpp
=> GSoC 2022: Sanskar Bhushan Week 7

include/ordering/cuthillMckeeOrdering.hpp, pgtap/ordering/cuthillMckeeOrdering/no_crash_test.pg
- Trying to make hpp file boost compatible
-
=> GSoC 2022 : Shobhit Chaurasia Week 8

include/ordering/cuthillMckeeOrdering.hpp, src/ordering/cuthillMckeeOrdering_driver.cpp
- Reverting previous approach, starting a fresh
- Made function compatible for boost function
-
=> GSoC 2022 : Shobhit Chaurasia Week 9

doc/src/pgRouting-introduction.rst
- Added name in the doc/src/pgRouting-introduction.rst
=> GSoC 2023: Aryan Gupta Week 1

doc/src/pgRouting-introduction.rst
- Added name in the doc/src/pgRouting-introduction.rst
=> GSoC 2023: Yige Huang Week 1

doc/src/pgRouting-introduction.rst, include/yen/pgr_ksp.hpp
Reverts pgRouting/GSoC-pgRouting#290
=> Revert "GSoC 2023: Aniket Agarwal Week 1"

include/drivers/yen/withPoints_ksp_driver.h, include/yen/pgr_ksp.hpp, src/ksp/withPoints_ksp.c, src/ksp/withPoints_ksp_driver.cpp
- Removing unused code
- Backward compatibility
=> GSoC 2023: Abhinav Jain Week 4

doc/ksp/pgr_KSP.rst, doc/src/migration.rst, docqueries/src/migration.result, docqueries/src/migration.test.sql, pgtap/ksp/ksp/no_crash_test.pg
=> GSoC 2023: Aniket Agarwal week 9

doc/driving_distance/pgr_drivingDistance.rst, doc/src/migration.rst, include/cpp_common/pgr_base_graph.hpp, include/dijkstra/v4drivingDist.hpp, pgtap/dijkstra/driving_distance/edge_cases/issue_1152.pg, pgtap/dijkstra/driving_distance/edge_cases/issue_519.pg, pgtap/dijkstra/driving_distance/inner_query.pg, pgtap/dijkstra/driving_distance/no_crash_test.pg, pgtap/dijkstra/driving_distance/types_check.pg
Fixes # .
-Fixed pgtap tests (Not the update test)
-Updated the documentation
-Updated the migration documentation
=> GSoC 2023: Aryan Gupta week 9

pgtap/ksp/ksp/inner_query.pg, pgtap/ksp/ksp/no_crash_test.pg, pgtap/ksp/ksp/types_check.pg, sql/scripts/build-extension-update-files.pl
- updated inner_query.pg
- updated no_crash.pg
- updated types_check.pg
- dropped pgr_ksp in build-extension-update-file  
=> GSoC 2023: Aniket Agarwal week 10

pgtap/ksp/withPointsKSP/inner_query.pg, pgtap/ksp/withPointsKSP/no_crash_test.pg, pgtap/ksp/withPointsKSP/types_check.pg, src/ksp/withPoints_ksp.c
- pgtap tests passes for previous version
=> GSoC 2023 : Abhinav Jain Week 10

doc/withPoints/pgr_withPointsDD.rst, pgtap/withPoints/withPointsDD/edge_cases/issue_979.pg, pgtap/withPoints/withPointsDD/edge_cases/undirected_driving_side.pg, pgtap/withPoints/withPointsDD/inner_query.pg, pgtap/withPoints/withPointsDD/no_crash_test.pg, sql/driving_distance/withPointsDD.sql, sql/scripts/build-extension-update-files.pl
- cherry-pick
- improve documentation
- fix SQL
=> GSoC 2023: YigeHuang week 10

.gitignore, doc/conf.py.in, doc/ksp/pgr_KSP.rst, doc/src/migration.rst, include/c_types/path_rt.h, include/cpp_common/basePath_SSEC.hpp, include/yen/pgr_ksp.hpp, src/common/basePath_SSEC.cpp, src/ksp/ksp.c, src/ksp/ksp_driver.cpp, src/ksp/withPoints_ksp.c, src/ksp/withPoints_ksp_driver.cpp
-  [doc] changes suggested by @cvvergara.
-  [KSP] changes suggested by @cvvergara.
=> GSoC 2023: Aniket Agarwal week 11

include/drivers/driving_distance/withPoints_dd_driver.h, src/driving_distance/many_to_dist_withPointsDD.c, src/driving_distance/withPoints_dd_driver.cpp
- removing duplicate code:
- include/drivers/driving_distance/withPoints_dd_driver.h
- src/driving_distance/many_to_dist_withPointsDD.c
- src/driving_distance/withPoints_dd_driver.cpp
=> GSoC 2023: Yige Huang week 11

doc/ksp/pgr_KSP.rst
=> GSoC 2023: Aniket Agarwal week 12

include/dijkstra/drivingDist.hpp, src/driving_distance/drivedist_driver.cpp
=> [drivingdistance][pgtap fix]

doc/src/migration.rst, doc/withPoints/pgr_withPointsDD.rst, pgtap/withPoints/withPointsDD/edge_cases/issue_979.pg, pgtap/withPoints/withPointsDD/edge_cases/undirected_driving_side.pg, sql/scripts/build-extension-update-files.pl
- modifying code with vicky's suggestion
- fixing update test
=> GSoC 2023: Yige Huang week 12

configuration.conf, doc/metrics/CMakeLists.txt, doc/metrics/metrics-family.rst, doc/metrics/pgr_centrality.rst, docqueries/metrics/CMakeLists.txt, docqueries/metrics/doc-centrality.result, docqueries/metrics/doc-centrality.test.sql, docqueries/metrics/test.conf, sql/metrics/CMakeLists.txt, sql/metrics/_centrality.sql, sql/metrics/_floydWarshall.sql, sql/metrics/centrality.sql, sql/metrics/floydWarshall.sql, src/metrics/CMakeLists.txt, src/metrics/centrality.c, src/metrics/centrality_driver.cpp
=> Centrality: Week 1

include/metrics/centrality.hpp, include/metrics/pgr_centrality.hpp, src/metrics/centrality_driver.cpp
=> centrality-week3

docqueries/metrics/CMakeLists.txt, docqueries/metrics/centrality.pg, docqueries/metrics/centrality.result, docqueries/metrics/test.conf, include/metrics/centrality.hpp, src/metrics/centrality_driver.cpp
=> Centrality Week 4

doc/metrics/pgr_betweennessCentrality.rst, docqueries/metrics/betweennessCentrality.pg, docqueries/metrics/betweennessCentrality.result
=> Centrality: Week 7

include/metrics/betweennessCentrality.hpp
=> Centrality week8

include/metrics/betweennessCentrality.hpp, pgtap/metrics/betweennessCentrality/edge_cases.pg, tools/scripts/code_checker.sh
-[x] Added all mandatory pgTap tests
-[x] Removed all linting errors from ```include/metrics/betweennessCentrality.hpp```
=> Centrality Week 10

include/metrics/betweennessCentrality.hpp
=> Centrality Week 11

include/c_types/metrics_rt.h, include/process/metrics_process.h, src/metrics/bandwidth.c, src/metrics/metrics_driver.cpp, src/metrics/metrics_process.cpp
Fixes # .
- Resolved Merge conflicts
- Reached a stable compiling point by updating/creating the following files :
- `include/c_types/metrics_rt.h`
- `include/drivers/metrics_driver.hpp`
- `include/process/metrics_process.h`
- `src/metrics/bandwidth.c`
- `src/metrics/metrics_driver.cpp`
- `src/metrics/metrics_process.cpp`
=> Week 3 bandwidth try3

docqueries/ordering/sloanOrdering.pg, docqueries/ordering/sloanOrdering.result, docqueries/ordering/test.conf, include/ordering/sloanOrdering.hpp, sql/ordering/sloanOrdering.sql, src/ordering/ordering_driver.cpp, src/ordering/sloanOrdering.c
Fixes # .
- Write boost function call for sloan ordering in sloanOrdering.hpp file
- Add result file for initial docqueries testing.
- Mark unneeded code.
- Resolve subsequent compilation errors.
=> Week 6 sloan ordering

docqueries/ordering/kingOrdering.result, docqueries/ordering/minDegreeOrdering.result, include/drivers/ordering_driver.hpp, include/ordering/ordering.hpp, include/process/ordering_process.h, src/ordering/CMakeLists.txt, src/ordering/kingOrdering.c, src/ordering/minDegreeOrdering.c, src/ordering/ordering_driver.cpp, src/ordering/ordering_process.cpp
=> Week 6 king and minimumdegree ordering

doc/ordering/pgr_sloanOrdering.rst, pgtap/ordering/sloan/edge_cases.pg
Fixes # .
- Add test query for 3 connected vertices in `edge_cases.pg`
- Modified the documentation files 
- Added example graph from boost
- Modify number of planned tests
=> week 10 sloan ordering

doc/src/pgRouting-introduction.rst
Fixes # .
- Added my name in pgrouting-introduction.rst
=> Week 12 bandwidth

doc/src/pgRouting-introduction.rst
Fixes # .
-
- Added name in `doc/src/pgRouting-introduction.rst` file
-
=> Week 12 sloan ordering
