pgRouting/GSoC-pgRouting

- doc/queries/doc-pgr_breadthFirstSearch.queries
- include/breadthFirstSearch/pgr_breadthFirstSearch.hpp
- pgtap/breadthFirstSearch/breadthFirstSearch-innerQuery.sql
- sql/breadthFirstSearch/breadthFirstSearch.sql
- src/breadthFirstSearch/breadthFirstSearch_driver.cpp
- test/breadthFirstSearch/doc-pgr_breadthFirstSearch.result
[WIP]
This PR is to track all the modifications done in Week 2.
> pgr_breadthFirstSearch GSOC-2019 week 2

- test/topologicalSort/doc-topologicalSort.test.sql
[WIP]
This PR is to track all the modifications done in Week 4.
> pgr_topologicalSort GSOC-2019 week 4

- include/binaryBreadthFirstSearch/pgr_binaryBreadthFirstSearch.hpp
- src/binaryBreadthFirstSearch/binaryBreadthFirstSearch_driver.cpp
[WIP]
This PR is to track all the modifications done in Week 7.
> pgr_binaryBreadthFirstSearch GSOC-2019 week 7

- include/edwardMoore/pgr_edwardMoore.hpp
- src/edwardMoore/edwardMoore_driver.cpp
[WIP]
This PR is to track all the modifications done in Week 10.
> pgr_edwardMoore GSOC-2019 week 10

- configuration.conf
- doc/depthFirstSearch/pgr_depthFirstSearch.rst
- doc/src/pgRouting-introduction.rst
- docqueries/depthFirstSearch/depthFirstSearch-issue1348-usage.result
- docqueries/depthFirstSearch/depthFirstSearch-issue1348-usage.test.sql
- docqueries/depthFirstSearch/doc-pgr_depthFirstSearch.result
- docqueries/depthFirstSearch/doc-pgr_depthFirstSearch.test.sql
- docqueries/depthFirstSearch/test.conf
- include/depthFirstSearch/pgr_depthFirstSearch.hpp
- src/depthFirstSearch/depthFirstSearch_driver.cpp
**Users' Documentation:**
* [`pgr_depthFirstSearch`](https://krashish8.github.io/GSoC-pgRouting/dev/en/pgr_depthFirstSearch.html)
**Developers' Documentation:**
1. [`pgrouting::functions::Pgr_depthFirstSearch()`](https://krashish8.github.io/GSoC-pgRouting/doxy/3.0/classpgrouting_1_1functions_1_1Pgr__depthFirstSearch.html#afedc84b74ba849fe0c15177812c27662)
2. [`depthFirstSearch.c`](https://krashish8.github.io/GSoC-pgRouting/doxy/3.0/depthFirstSearch_8c.html)
3. [`depthFirstSearch_driver.cpp`](https://krashish8.github.io/GSoC-pgRouting/doxy/3.0/depthFirstSearch__driver_8cpp.html)
4. [`depthFirstSearch_driver.h`](https://krashish8.github.io/GSoC-pgRouting/doxy/3.0/depthFirstSearch__driver_8h.html)
> pgr_depthFirstSearch GSoC-2020 Week [1] 

- pgtap/depthFirstSearch/depthFirstSearch-edge-cases.sql
- pgtap/depthFirstSearch/depthFirstSearch-rows-check.sql
- pgtap/graphColoring/no_crash_test-sequentialVertexColoring.sql
- pgtap/graphColoring/sequentialVertexColoring-edge-cases.sql
- pgtap/graphColoring/sequentialVertexColoring-innerQuery.sql
- pgtap/graphColoring/sequentialVertexColoring-rows-check.sql
- pgtap/graphColoring/sequentialVertexColoring-typesCheck.sql
> pgr_sequentialVertexColoring GSoC-2020 Week 6

- include/cpp_common/pgr_base_graph.hpp
Fixes #70.
- Adds code that sorts the edges of the graph before creating it.
- Sorting in terms of SQL is `ORDER BY id, source, target`
> Closes #70 adds code that sorts the edges

- pgtap/allpairs/floydWarshall-rows-check.sql
- pgtap/allpairs/johnson-rows-check.sql
Fixes #69.
- Adds pgTAP tests for allpairs that check the output after rows ordering.
> Closes #69 adds allpairs pgtap tests to check output after rows ordering

- pgtap/chinese/chinesePostman/chinesePostman-rows-check.sql
- pgtap/chinese/chinesePostmanCost/chinesePostmanCost-rows-check.sql
Fixes #75 
- Adds pgTAP tests for chinese postman that check the output after rows ordering.
> Closes #75 adds chinese postman pgtap tests to check output after row ordering

- pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-rows-check.sql
- pgtap/breadthFirstSearch/breadthFirstSearch/breadthFirstSearch-rows-check.sql
- src/breadthFirstSearch/binaryBreadthFirstSearch_driver.cpp
- src/breadthFirstSearch/breadthFirstSearch_driver.cpp
Fixes #78.
- Adds pgTAP tests for breadthFirstSearch that check the output after rows ordering.
-
-
> Closes #78 fixing breadthFirstSearch ordering issue

- pgtap/astar/aStarCost-rows-check.sql
- pgtap/astar/astar-rows-check.sql
- src/astar/astar_driver.cpp
astar on #68
- Adds pgTAP tests for astar algorithm that check the output after rows ordering.
- Fixes the code, by calling the function that sorts the input rows before creating the graph.
> Fixing astar ordering issue

- pgtap/dagShortestPath/dagShortestPath-rows-check.sql
- src/dagShortestPath/dagShortestPath_driver.cpp
dagShortestPath on #68.
- Adds pgTAP tests for dagShortestPath directory that check the output after rows ordering.
> Fixing dagShortestPath ordering issue

- pgtap/contraction/contraction-rows-check.sql
- src/contraction/contractGraph_driver.cpp
contraction on #68.
- Adds pgTAP tests for contraction directory that check the output after rows ordering.
> Fixing contraction ordering issue

- pgtap/bdDijkstra/bdDijkstra-rows-check.sql
- pgtap/bdDijkstra/bdDijkstraCost-rows-check.sql
- src/bdDijkstra/bdDijkstra_driver.cpp
bdDijkstra on #68.
- Adds pgTAP tests for bdDijkstra directory that check the output after rows ordering.
- Fixes the code, by calling the function that sorts the input rows before creating the graph.
> Fixing bdDijkstra ordering issue

- pgtap/costMatrix/aStarCostMatrix/aStarCostMatrix-rows-check.sql
- pgtap/costMatrix/bdAstarCostMatrix/bdAstarCostMatrix-rows-check.sql
- pgtap/costMatrix/bdDijkstraCostMatrix/bdDijkstraCostMatrix-rows-check.sql
- pgtap/costMatrix/dijkstraCostMatrix/dijkstraCostMatrix-rows-check.sql
- pgtap/costMatrix/withPointsCostMatrix/withPointsCostMatrix-rows-check.sql
costMatrix on #68.
- Adds pgTAP tests for costMatrix directory that check the output after rows ordering.
> Fixing costMatrix ordering issue

- pgtap/driving_distance/dijkstraDD-rows-check.sql
- pgtap/driving_distance/withPointsDD-rows-check.sql
- src/driving_distance/drivedist_driver.cpp
driving_distance on #68.
- Adds pgTAP tests for driving_distance directory that check the output after rows ordering.
> Fixing driving_distance ordering issue

- pgtap/mincut/stoerWagner-rows-check.sql
mincut on #68.
- Adds pgTAP tests for mincut directory that check the output after rows ordering.
> Fixing mincut ordering issue

- pgtap/spanningTree/kruskal/kruskal/kruskal-rows-check.sql
- pgtap/spanningTree/kruskal/kruskalBFS/kruskalBFS-rows-check.sql
- pgtap/spanningTree/kruskal/kruskalDD/kruskalDD-rows-check.sql
- pgtap/spanningTree/kruskal/kruskalDFS/kruskalDFS-rows-check.sql
- pgtap/spanningTree/prim/prim/prim-rows-check.sql
- pgtap/spanningTree/prim/primBFS/primBFS-rows-check.sql
- pgtap/spanningTree/prim/primDD/primDD-rows-check.sql
- pgtap/spanningTree/prim/primDFS/primDFS-rows-check.sql
- src/spanningTree/kruskal_driver.cpp
- src/spanningTree/prim_driver.cpp
spanningTree on #68.
- Adds pgTAP tests for spanningTree directory that check the output after rows ordering.
> Fixing spanningTree ordering issue

- pgtap/topology/extractVertices/extractVertices-rows-check.sql
topology on #68.
- Adds pgTAP tests for topology directory that check the output after rows ordering.
> Fixing topology ordering issue

- pgtap/topologicalSort/topologicalSort-rows-check.sql
- src/topologicalSort/topologicalSort_driver.cpp
topologicalSort on #68.
- Adds pgTAP tests for topologicalSort directory that check the output after rows ordering.
> Fixing topologicalSort ordering issue

- pgtap/transitiveClosure/transitiveClosure-rows-check.sql
- src/transitiveClosure/transitiveClosure_driver.cpp
transitiveClosure on #68.
- Adds pgTAP tests for transitiveClosure directory that check the output after rows ordering.
> Fixing transitiveClosure ordering issue

- .github/workflows/ubuntu.yml
- CMakeLists.txt
- include/c_common/vroom/breaks_input.h
- include/c_common/vroom/jobs_input.h
- include/c_common/vroom/shipments_input.h
- include/c_common/vroom/steps_input.h
- include/c_common/vroom/time_windows_input.h
- include/c_common/vroom/vehicles_input.h
- src/common/vroom/breaks_input.c
- src/common/vroom/jobs_input.c
- src/common/vroom/shipments_input.c
- src/common/vroom/steps_input.c
- src/common/vroom/time_windows_input.c
- src/common/vroom/vehicles_input.c
- src/vroom/vroom.c
- src/vroom/vroom_driver.cpp
- Added functions to get the postgres datatypes and convert them to vroom C types.
- Breaks input
- Steps input
- Time Windows input
- Jobs input
- Shipments input
- Vehicles input
- Created basic skeleton to take the inputs in `vroom.c` and pass them to the vroom driver function.
- Updated CMakeLists to build and compile vrprouting with vroom.
- Updated GitHub actions scripts for Ubuntu to build VROOM.
> GSoC-2021 Week 2: vrp_vroom

- include/cpp_common/vrp_vroom_problem.hpp
- src/common/CMakeLists.txt
- Added vroom types input in CMakeLists.
- Add functions to connect VROOM to vrprouting
-
> GSoC-2021 Week 4: vrp_vroom

- pgtap/vroom/inner_query.sql
- pgtap/vroom/no_crash_test.sql
- pgtap/vroom/types_check.sql
- src/common/get_check_data.c
- tools/testers/setup_db.sql
- tools/testers/vroomdata.sql
- Added vroomdata for pgtap tests
- Added types check
- Added no crash test
- Added inner query test for vrp_vroom
- Fixed spi_getText for NULL values
> GSoC-2021 Week-7: vrp_vroom

- configuration.conf
- doc/circuits/CMakeLists.txt
- include/c_types/circuits_rt.h
- include/circuits/hawickcircuits.hpp
- include/drivers/circuits/hawickcircuits_driver.h
- sql/circuits/CMakeLists.txt
- src/circuits/CMakeLists.txt
- created the function logic header file
- fixed some linting errors 
- uncommenting the CMake lists and adding the circuit to the configuration file
> GSoC 2022: Nitish Chauhan Week 3

- include/ordering/cuthillMckeeOrdering.hpp
- src/ordering/cuthillMckeeOrdering_driver.cpp
- Initial tries for solving graph type error
- Graph type is solved but need to change a lot of code yet.
> GSoC 2022 : Shobhit Chaurasia Week 7

- docqueries/ordering/cuthillMckeeOrdering.result
- docqueries/ordering/cuthillMckeeOrdering.test.sql
- include/ordering/cuthillMckeeOrdering.hpp
- pgtap/ordering/cuthillMckeeOrdering/edge_cases.pg
- pgtap/ordering/cuthillMckeeOrdering/no_crash_test.pg
- src/ordering/cuthillMckeeOrdering_driver.cpp
- Wrong result and approach
-
-
> GSoC 2022 : Shobhit Chaurasia

- pgtap/circuits/hawickCircuits/edge_cases.pg
- Change edge cases to previous sample data
> GSoC 2022: Nitish Chauhan Week 11

- .gitignore
- doc/src/pgRouting-introduction.rst
- include/c_types/path_rt.h
- include/drivers/yen/ksp_driver.h
- include/yen/pgr_ksp.hpp
- sql/ksp/_ksp.sql
- sql/ksp/ksp.sql
- src/common/basePath_SSEC.cpp
- src/ksp/ksp.c
- src/ksp/ksp_driver.cpp
Added overloads:
- one to many
- many to one
- many to many
- combinations
> GSoC 2023: Aniket Agarwal Week 2

- include/drivers/yen/withPoints_ksp_driver.h
- include/yen/pgr_ksp.hpp
- src/ksp/withPoints_ksp.c
- src/ksp/withPoints_ksp_driver.cpp
> GSoC 2023 - Abhinav Jain Week 2

- .gitignore
- include/c_types/path_rtdd.h
- include/dijkstra/v4drivingDist.hpp
- include/drivers/driving_distance/v4drivedist_driver.h
- sql/driving_distance/_drivingDistance.sql
- sql/driving_distance/drivingDistance.sql
- src/driving_distance/v4drivedist_driver.cpp
- src/driving_distance/v4driving_distance.c
Fixes # .
-added a new structure path_rtdd
-made some new v4 files 
-adjusted function names
> GSoC 2023: Aryan Gupta week 4

- include/drivers/driving_distance/withPoints_dd_driver.h
- include/driving_distance/withPointsDD.hpp
- sql/driving_distance/_withPointsDD.sql
- sql/driving_distance/withPointsDD.sql
- src/driving_distance/v4withPointsDD.c
- src/driving_distance/v4withPoints_dd_driver.cpp
- Finish the work of adding new output column `depth`. Details: 
-  /src/driving_distance/v4withPointsDD.c & v4withPoints_dd_driver.cpp: 
- To include the `depth` property, changed the type of `result_tuples` from `Path_rt**` to `MST_rt**`
-  /include/driving_distancewithPointsDD.hpp: 
- Calculate `depth` base on the returns of `pgr_drivingDistance` . more details can be found in [week-4-PR](https://github.com/pgRouting/GSoC-pgRouting/pull/309)
- Tested locally and got correct results.
> GSoC 2023: Yige Huang Week 5

- docqueries/withPoints/CMakeLists.txt
- docqueries/withPoints/test.conf
- include/cpp_common/basePath_SSEC.hpp
- src/common/basePath_SSEC.cpp
- src/ksp/withPoints_ksp_driver.cpp
Fixes # .
Bug Fixes in Start Column
> GSoC 2023: Abhinav Jain Week 5

- docqueries/withPoints/doc-pgr_withPointsDD.result
- include/drivers/driving_distance/withPoints_dd_driver.h
- sql/driving_distance/withPointsDD.sql
- sql/sigs/pgrouting--3.6.sig
- src/driving_distance/v4withPointsDD.c
- src/driving_distance/v4withPoints_dd_driver.cpp
- Checked driving side at SQL level instead of C/C++ level.
- In order to pass the test：
- updated signatures.
- updated `docqueries/withPoints/doc-pgr_withPointsDD.result`
- fixed bug.
> GSoC 2023: Yige Huang Week 6

- .gitignore
- pgtap/ksp/ksp/inner_query.pg
- pgtap/ksp/ksp/no_crash_test.pg
- sql/ksp/_ksp.sql
- sql/ksp/ksp.sql
- src/common/basePath_SSEC.cpp
- updated following pagtap tests files: 
- no_crash_test
- inner_query
> GSoC 2023: Aniket Agarwal week 8

- doc/src/migration.rst
- doc/withPoints/pgr_withPointsDD.rst
- docqueries/src/migration.result
- docqueries/src/migration.test.sql
- Update to pgr_withPoints DD documentation
- Modified the description of `driving side`
- Migration guide for pgr_withPointsDD
> GSoC 2023: Yige Huang week 9

- pgtap/metrics/types_check.pg
- added pgtap folder and types_check.pg
-
> Centrality-Week8 (correction)

- docqueries/ordering/kingOrdering.pg
- include/ordering/ordering.hpp
- src/ordering/ordering_driver.cpp
> Week 7 king minimum ordering

- docqueries/ordering/sloanOrdering.pg
- docqueries/ordering/sloanOrdering.result
- include/ordering/sloanOrdering.hpp
- src/ordering/ordering_driver.cpp
- src/ordering/sloanOrdering.c
Fixes # .
- Make necessary changes in the sloanOrdering.hpp file to call the correct boost function call.
- Add sloan ordering version without weighted graph support.
- Fix existing errors in ordering_driver.cpp file and make the previously disabled code reach a compilable stage.
- Fix necessary code alignment and style issues.
- Call the get_results function to generate results table from function call.
- Remove unrequired code block from sloanOrdering.c file and modified the logic for calling boost function.
- Add example boost query to sloanOrdering.pg file in docqueries/ordering.
> Week 7 sloanordering

- .gitignore
- docqueries/ordering/kingOrdering.result
- include/ordering/kingOrdering.hpp
- include/ordering/minDegreeOrdering.hpp
- src/ordering/ordering_driver.cpp
> Week 11 king minimum ordering
